### ISSUE TITLE
SVG format doesn't respect size attribute.

### ISSUE THREAD

**Issue by shahzeb1** [tobiaslins/avatar#2]
> https://avatar.tobi.sh/tobiaslins?size=500&type=svg

When both `size` and `type` arguments are given, the format is correct (SVG), but the size of the SVG is not changed by the "500" which is being passed in.

### Fix:
Change https://github.com/tobiaslins/avatar/blob/master/src/svg.js#L3 so that `width="120" height="120"` is changed to `width="[size]" height="[size]"`

**Comment by tobiaslins** [comment]
thanks for your idea :)

Feature is live: 
![SVG](https://avatar.tobi.sh/test.svg?size=25)
