### ISSUE TITLE
File extension influences avatar

### ISSUE THREAD

**Issue by timolins** [tobiaslins/avatar#4]
This bug doesn't occur with GET parameters, only with custom extensions.

`https://avatar.tobi.sh/timo.jpg`

![](https://avatar.tobi.sh/timo.jpg)

`https://avatar.tobi.sh/timo.png`

![](https://avatar.tobi.sh/timo.png)

**Comment by hugomd** [comment]
Isn't this expected? As far as I know, avatar doesn't support the `jpg` extension.

In the first case, `timo.jpg` is the input.

In the second case, `timo` is the input, as `png` is the reserved file extension

A possible fix would be to ignore all extensions, but that would restrict the domain of inputs..

**Comment by timolins** [comment]
You are right. `jpg` is unsupported, so it doesn't get ignored either. Makes sense, I guess.
