### ISSUE TITLE
Since migration from avatar.tobi.sh the text attribute is missing from the avatar

### ISSUE THREAD

**Issue by fabiobaser** [tobiaslins/avatar#46]
[https://avatar.tobi.sh/tobiaslins.svg?text=TL](https://avatar.tobi.sh/tobiaslins.svg?text=TL) would generate an avatar with the initials "TL" in white letters on top of the gradient. The new Docs even describe this behavior, but it is simply missing completely.

**Comment by xlab** [comment]
As of now, seems to be working just fine https://avatar.vercel.sh/tobiaslins.svg?text=TL

**Comment by styfle** [comment]
Closing as "can't repro"
