### ISSUE TITLE
Image Generation No Longer working

### ISSUE THREAD

**Issue by awtkns** [tobiaslins/avatar#48]
It seems that since #45 image generation has ceased to work. Even the homepage does not look to be working correctly.

<img width="466" alt="Screen Shot 2023-04-27 at 9 47 42 PM" src="https://user-images.githubusercontent.com/32209255/234987455-4ff0600b-58df-46b2-b3ed-be6c06b8e03a.png">

**Comment by awtkns** [comment]
cc @pontusab i think this may be related to your changes in #45

**Comment by pontusab** [comment]
oh yeah, I will have a look!
