### ISSUE TITLE
Size can only be a square

### ISSUE THREAD

**Issue by ulrichformann** [tobiaslins/avatar#6]
size=300 returns a 300x300 image while size=300x300 returns a 120x120px image. 
It would be nice to set width as well as the height.

**Comment by tobiaslins** [comment]
@ulrichformann in which scenario do you need a non square gradient/avatar?

**Comment by ulrichformann** [comment]
For instance cover images to support the avatar or placeholders for non-square avatars like portraits

**Comment by ulrichformann** [comment]
@tobiaslins check out my [fork](https://github.com/ulrichformann/avatar) where i implemented this feature and tell me whether you like it or it doesn't work with your vision for this app
